[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

# Additional configurations for deployment (if necessary)
# Uncomment the following lines if you wish to enable specific features
# [functions]
#   directory = "netlify/functions"
